Defect 1:

    Burst count = 35  --  Neuron count in FCL is 6
        vision_v1-4 : 1
        vision_v2 : 1
        vision_v1-1 : 3
        vision_v1-7 : 1
    >>> Burst duration: 0:00:00.001732
    Burst count = 36  --  Neuron count in FCL is 55
        vision_v2 : 54
        vision_IT : 1
    Process SpawnPoolWorker-15:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
        self.run()
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 103, in worker
        initializer(*initargs)
      File "/Users/MNT/PycharmProjects/Metis/neuron_functions.py", line 90, in burst
        neuron_fire(x[0], x[1])
      File "/Users/MNT/PycharmProjects/Metis/neuron_functions.py", line 212, in neuron_fire
        universal_functions.brain[cortical_area][id]["neighbors"][x]["postsynaptic_potential"], x)
      File "/Users/MNT/PycharmProjects/Metis/neuron_functions.py", line 271, in neuron_update
        "%Y-%m-%d %H:%M:%S.%f") + datetime.timedelta(0,
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
        tt, fraction = _strptime(data_string, format)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_strptime.py", line 362, in _strptime
        (data_string, format))
    ValueError: time data '2017-12-01 11:42:02' does not match format '%Y-%m-%d %H:%M:%S.%f'